### PR TITLE
Custom notifier

### PR DESCRIPTION
**Pull request by sahilgan**
I implemented simple email notifier (based on 'emails' package) and added a wrapper class
That could be useful when chameleon's running on air-gapped systems

### CODE REVIEW

**Comment by the4thdoctor** [comment]
Can you please use tabs instead of spaces?

I will draft the guidelines for contributing to this project which include tabs set at 4 spaces for anything but yaml and no camel case for the function's names.
Thanks

**Comment by sahilgan** [comment]
Fixed indentation

**Comment by the4thdoctor** [comment]
tanks for the contribution. I'll test the change ASAP :)

**Comment by sahilgan** [comment]
Federico, why don't you want to accept the contribution? 
Tell me please how to make it more convinient

**Comment by the4thdoctor** [comment]
Sorry, I went through hard times which kept me away from the project. 
I'm slowly picking up again the development and I'll test your contribution soon.

**Pull request closed without merging**
